### ISSUE TITLE
Module is not usable on Elasticsearch 5.x and x-pack

### ISSUE THREAD

**Issue by jjm** [elastic/elasticsearch-watcher-py#1]
Hi,

When using this module against Elasticsearch 5.2+ when using the following line of code (taken from the README):

```python
print('Using watcher', es.watcher.info()['version']['number'])
```

Produces a `Traceback` that ends with the following:

```python
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'No endpoint or operation is available at [_watcher]')
```

Looking over the current documents for `x-pack` the version information is not exposed by the API and in fact all the API end points now have new locations and the documentation URLs in the module are also broken.

By the looks of things, the module has not bee updated to support x-pack and needs some updates to make it work with the current version of Elasticsearch and x-pack.

Would a PR be acceptable? I'm looking at deploying xpack alerting and this module would make the task alot easier.

**Comment by honzakral** [comment]
Hi, `watcher` is the name of the plugin for past version of elasticsearch, since it has been renamed to `x-pack` we also created a new python library - https://github.com/elastic/elasticsearch-x-pack-py - that supports all the `x-pack` APIs.

I will add the info to the readme.

**Comment by jjm** [comment]
Thanks @HonzaKral, the new xpack module is proving useful.
